const films: { title: string }[] = [
  { title: `Anchorman: The Legend of Ron Burgundy` },
  { title: `Anchorman 2: The Legend Continues` },
  { title: `Batman Begins` },
  { title: `Beerfest` },
  { title: `Bill & Ted's Excellent Adventure` },
  { title: `Blazing Saddles` },
  { title: `The Cabin in the Woods` },
  { title: `The Campaign` },
  { title: `Castle in the Sky` },
  { title: `Coco` },
  { title: `The Dark Knight` },
  { title: `THe Dark Knight Rises` },
  { title: `Dodgeball` },
  { title: `Dumb and Dumber` },
  { title: `Employee of the Month` },
  { title: `Fast Times at Ridgemont High` },
  { title: `Fight Club` },
  { title: `Get Hard` },
  { title: `Godzilla` },
  { title: `The Hangover Part II` },
  { title: `Harry Potter and the Sorcerer's Stone` },
  { title: `Harry Potter and the Chamber of Secrets` },
  { title: `Harry Potter and the Prisoner of Azkaban` },
  { title: `Harry Potter and the Goblet of Fire` },
  { title: `Harry Potter and the Order of the Phoenix` },
  { title: `Harry Potter and the Half-Blood Prince` },
  { title: `Harry Potter and the Deathly Hallows Part 1` },
  { title: `Harry Potter and the Deathly Hallows Part 2` },
  { title: `The Hateful Eight` },
  { title: `The Hobbit: An Unexpected Journey` },
  { title: `The Hobbit: The Desolation of Smaug` },
  { title: `The Hobbit: The Battle of the Five Armies` },
  { title: `High Anxiety` },
  { title: `History of the World Part I` },
  { title: `Horrible Bosses` },
  { title: `Horrible Bosses 2` },
  { title: `Hot Fuzz` },
  { title: `Inception` },
  { title: `Independence Day` },
  { title: `Inglorious Basterds` },
  { title: `Interstellar` },
  { title: `Jurassic Park` },
  { title: `The Lost World: Jurassic Park` },
  { title: `Jurassic Park III` },
  { title: `Jurassic World` },
  { title: `Jurassic World: Fallen Kingdom` },
  { title: `Kiki's Delivery Service` },
  { title: `Kill Bill Volume 1` },
  { title: `Kill Bill Volume 2` },
  { title: `Kung Pow: Enter the Fist` },
  { title: `The Last Samurai` },
  { title: `Lilo & Stitch` },
  { title: `The Lord of the Rings: The Fellowship of the Ring` },
  { title: `The Lord of the Rings: The Two Towers` },
  { title: `The Lord of the Rings: The Return of the King` },
  { title: `The Matrix` },
  { title: `The Matrix: Reloaded` },
  { title: `The Matrix: Revolutions` },
  { title: `Monty Python and the Holy Grail` },
  { title: `Moana` },
  { title: `The Mummy` },
  { title: `The Mummy Returns` },
  { title: `The Mummy: Tomb of the Dragon Emperor` },
  { title: `My Neighbor Totoro` },
  { title: `Nacho Libre` },
  { title: `Nausicaa of the Valley of the Wind` },
  { title: `No Country for Old Men` },
  { title: `Old School` },
  { title: `The Other Guys` },
  { title: `Pacific Rim` },
  { title: `Porco Rosso` },
  { title: `Princess Mononoke` },
  { title: `The Phantom of the Opera` },
  { title: `Pulp Fiction` },
  { title: `The Ring` },
  { title: `Robin Hood: Men in Tights` },
  { title: `Rogue One: A Star Wars Story` },
  { title: `Santa's Magical Stories` },
  { title: `The Scorpion King` },
  { title: `Shaun of the Dead` },
  { title: `Silent Movie` },
  { title: `Spaceballs` },
  { title: `Spirited Away` },
  { title: `Star Wars Episode IV: A New Hope` },
  { title: `Star Wars Episode V: The Empire Strikes Back` },
  { title: `Star Wars Episode VI: Return of the Jedi` },
  { title: `Star Wars Episode I: The Phantom Menace` },
  { title: `Star Wars Episode II: Attack of the Clones` },
  { title: `Star Wars Episode III: Revenge of the Sith` },
  { title: `Step Brothers` },
  { title: `Superbad` },
  { title: `Talladega Nights: The Ballad of Ricky Bobby` },
  { title: `To Be or Not to Be` },
  { title: `Total Recall` },
  { title: `Transformers` },
  { title: `The Twelve Chairs` },
  { title: `V for Vendetta` },
  { title: `The Watch` },
  { title: `Wedding Crashers` },
  { title: `The World's End` },
  { title: `Young Frankenstein` },
  { title: `Zootopia` }
 ]

 export { films };
