version: '3.3'
services:
  db:
    image: mysql:8
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'strongpw'
      MYSQL_ROOT_PASSWORD: 'rewt'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - sqldb:/var/lib/mysql
  app:
    build: .
    image: node:14-alpine
    container_name: node
    ports:
      - 3000:3000
    expose:
      - '3000'
    depends_on:
      - db
    tty: true
volumes:
  sqldb:
