version: '3'
services:
  db:
    image: mysql:8
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: '${DB}'
      MYSQL_USER: '${USR}'
      MYSQL_PASSWORD: '${PSSWRD}'
      MYSQL_ROOT_PASSWORD: '${RTPSSWRD}'
    ports:
      - '3306:3306'
    networks:
      - default
    volumes:
      - sqldb:/var/lib/mysql
      - ./docker/src/db:/docker-entrypoint-initdb.d
  app:
    build: ./docker
    image: node:14-alpine
    container_name: node
    ports:
      - 3000:3000
    networks:
      default:
        aliases:
          - theapp
    depends_on:
      - db
    tty: true
    volumes:
      - ./docker:/HomeVideos
      - ../prvkey:/key
volumes:
  sqldb:
