const films = [
  [`Anchorman: The Legend of Ron Burgandy`],
  [`Anchorman 2: The Legend Continues`],
  [`Batman Begins`],
  [`Beerfest`],
  [`Bill & Ted's Excellent Adventure`],
  [`Blazing Saddles`],
  [`The Cabin in the Woods`],
  [`The Campaign`],
  [`Castle in the Sky`],
  [`Coco`],
  [`The Dark Knight`],
  [`THe Dark Knight Rises`],
  [`Dodgeball`],
  [`Dumb and Dumber`],
  [`Employee of the Month`],
  [`Fast Times at Ridgemont High`],
  [`Fight Club`],
  [`Get Hard`],
  [`Godzilla`],
  [`The Hangover Part II`],
  [`Harry Potter and the Sorcerer's Stone`],
  [`Harry Potter and the Chamber of Secrets`],
  [`Harry Potter and the Prisoner of Azkaban`],
  [`Harry Potter and the Goblet of Fire`],
  [`Harry Potter and the Order of the Phoenix`],
  [`Harry Potter and the Half-Blood Prince`],
  [`Harry Potter and the Deathly Hallows Part 1`],
  [`Harry Potter and the Deathly Hallows Part 2`],
  [`The Hateful Eight`],
  [`The Hobbit: An Unexpected Journey`],
  [`The Hobbit: The Desolation of Smaug`],
  [`The Hobbit: The Battle of the Five Armies`],
  [`High Anxiety`],
  [`History of the World Part I`],
  [`Horrible Bosses`],
  [`Horrible Bosses 2`],
  [`Hot Fuzz`],
  [`Inception`],
  [`Independence Day`],
  [`Inglorious Basterds`],
  [`Interstellar`],
  [`Jurassic Park`],
  [`The Lost World: Jurassic Park`],
  [`Jurassic Park III`],
  [`Jurassic World`],
  [`Jurassic World: Fallen Kingdom`],
  [`Kiki's Delivery Service`],
  [`Kill Bill Volume 1`],
  [`Kill Bill Volume 2`],
  [`Kung Pow: Enter the Fist`],
  [`The Last Samurai`],
  [`Lilo & Stitch`],
  [`The Lord of the Rings: The Fellowship of the Ring`],
  [`The Lord of the Rings: The Two Towers`],
  [`The Lord of the Rings: The Return of the King`],
  [`The Matrix`],
  [`The Matrix: Reloaded`],
  [`The Matrix: Revolutions`],
  [`Monty Python and the Holy Grail`],
  [`Moana`],
  [`The Mummy`],
  [`The Mummy Returns`],
  [`The Mummy: Tomb of the Dragon Emperor`],
  [`My Neighbor Totoro`],
  [`Nacho Libre`],
  [`Nausicaa of the Valley of the Wind`],
  [`No Country for Old Men`],
  [`Old School`],
  [`The Other Guys`],
  [`Pacific Rim`],
  [`Porco Rosso`],
  [`Princess Mononoke`],
  [`The Phantom of the Opera`],
  [`Pulp Fiction`],
  [`The Ring`],
  [`Robin Hood: Men in Tights`],
  [`Rogue One: A Star Wars Story`],
  [`Santa's Magical Stories`],
  [`The Scorpion King`],
  [`Shaun of the Dead`],
  [`Silent Movie`],
  [`Spaceballs`],
  [`Spirited Away`],
  [`Star Wars Episode IV: A New Hope`],
  [`Star Wars Episode V: The Empire Strikes Back`],
  [`Star Wars Episode VI: Return of the Jedi`],
  [`Star Wars Episode I: The Phantom Menace`],
  [`Star Wars Episode II: Attack of the Clones`],
  [`Star Wars Episode III: Revenge of the Sith`],
  [`Step Brothers`],
  [`Superbad`],
  [`Talladega Nights: The Ballad of Ricky Bobby`],
  [`To Be or Not to Be`],
  [`Total Recall`],
  [`Transformers`],
  [`The Twelve Chairs`],
  [`V for Vendetta`],
  [`The Watch`],
  [`Wedding Crashers`],
  [`The World's End`],
  [`Young Frankenstein`],
  [`Zootopia`]
]

module.exports = { films };
